## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head(30)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Saint Anthony,US,80.91,clear sky,45.0205,-93.2180,Holiday Inn Express Roseville-St. Paul
1,2,Vaini,TO,78.96,broken clouds,-21.2000,-175.2000,Keleti Beach Resort
2,6,Viransehir,TR,88.61,clear sky,37.2353,39.7631,Viranşehir Öğretmenevi
3,14,Butaritari,KI,82.87,broken clouds,3.0707,172.7902,Isles Sunset Lodge
4,21,Tupelo,US,82.69,clear sky,34.2576,-88.7034,"Hilton Garden Inn Tupelo, MS"
5,26,San Juan De Uraba,CO,76.15,overcast clouds,8.7592,-76.5297,Hotel Cerro De Zumba
6,28,Pandan,PH,86.31,moderate rain,14.0453,124.1694,Bonifacio Lodge
7,34,Atuona,PF,77.74,few clouds,-9.8000,-139.0333,Villa Enata
8,46,Tuy Hoa,VN,88.92,overcast clouds,13.0833,109.3000,CenDeluxe Hotel Tuy Hoa
9,52,Avarua,CK,75.25,broken clouds,-21.2078,-159.7750,Paradise Inn
10,55,Victoria,HK,88.25,overcast clouds,22.2855,114.1577,Mini Central
11,59,Bahia Honda,CU,78.64,clear sky,22.9036,-83.1592,Casa Gualberto - Deysi
12,60,Susaki,JP,85.60,scattered clouds,33.3667,133.2833,Awa
13,62,Baturaja,ID,87.35,scattered clouds,-4.1333,104.1667,"HOTEL Sekar Sunja, Baturaja Timur, Ogan Komeri..."
14,65,Bethel,US,77.90,clear sky,41.3712,-73.4140,Courtyard by Marriott Danbury
15,69,Tsagan Aman,RU,82.13,overcast clouds,47.5639,46.7218,Tirupathi
16,71,Georgetown,MY,85.95,few clouds,5.4112,100.3354,Cititel Penang
17,74,Plymouth,US,76.82,clear sky,41.8334,-70.8328,Rodeway Inn Middleboro-Plymouth
18,75,Batticaloa,LK,86.59,overcast clouds,7.7102,81.6924,Grand Star Guest House
19,82,Hithadhoo,MV,82.27,broken clouds,-0.6000,73.0833,Scoop Guest House
20,86,Castiglione Del Lago,IT,75.11,clear sky,43.1271,12.0453,Hotel Trasimeno
21,91,Hilo,US,85.28,overcast clouds,19.7297,-155.0900,Hilo Hawaiian Hotel
22,92,Sao Filipe,CV,77.27,overcast clouds,14.8961,-24.4956,Hotel Xaguate
23,93,Hue,VN,87.91,light rain,16.4667,107.6000,Saigon Morin Hotel
24,98,Cacoal,BR,77.72,light rain,-11.4386,-61.4472,Hotel BR 364
25,99,Lichuan,CN,82.44,scattered clouds,30.3000,108.8500,Yuanlai Homestay
26,101,Monrovia,LR,75.65,overcast clouds,6.3005,-10.7969,Sunset Inn
27,107,Kahului,US,87.82,few clouds,20.8947,-156.4700,Maui Seaside Hotel
28,118,Cabo San Lucas,MX,87.62,broken clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos
29,126,Bardiyah,LY,77.38,clear sky,31.7561,25.0865,بورتو بردية

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """ <dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
vacation_start = vacation_df.loc[vacation_df["City"]=="Xining"]
vacation_start["Lat"].to_numpy()[0]

36.6167

In [6]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"]=="Genhe"]
vacation_end = vacation_df.loc[vacation_df["City"]=="Genhe"]
vacation_stop1 = vacation_df.loc[vacation_df["City"]=="Hulan Ergi"]
vacation_stop2 = vacation_df.loc[vacation_df["City"]=="Dongsheng"]
vacation_stop3 = vacation_df.loc[vacation_df["City"]=="Xining"]

In [7]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = (vacation_start["Lat"].to_numpy()[0],vacation_start["Lng"].to_numpy()[0])
end = (vacation_end["Lat"].to_numpy()[0],vacation_end["Lng"].to_numpy()[0])
stop1 = (vacation_stop1["Lat"].to_numpy()[0],vacation_stop1["Lng"].to_numpy()[0])
stop2 = (vacation_stop2["Lat"].to_numpy()[0],vacation_stop2["Lng"].to_numpy()[0])
stop3 = (vacation_stop3["Lat"].to_numpy()[0],vacation_stop3["Lng"].to_numpy()[0])

In [8]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig =gmaps.figure()
city_itinerary = gmaps.directions_layer(start,end,waypoints=[stop1,stop2,stop3],
travel_mode="DRIVING")
fig.add_layer(city_itinerary)
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,338,Genhe,CN,76.73,scattered clouds,50.7833,121.5167,Companionship Hotel
1,578,Hulan Ergi,CN,84.83,broken clouds,47.2042,123.6333,Qiqihaer Zhongtian Hotel
2,604,Dongsheng,CN,87.57,broken clouds,39.8161,109.9776,Crowne Plaza Ordos
3,458,Xining,CN,78.80,scattered clouds,36.6167,101.7667,Super Leisure Hotel

In [10]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>


"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]
hotel_info

['<dl>\n<dt>Hotel Name</dt><dd>Companionship Hotel</dd>\n<dt>City</dt><dd>Genhe</dd>\n<dt>Country</dt><dd>CN</dd>\n<dt>Max Temp</dt><dd>76.73 °F</dd>\n</dl>\n\n\n',
 '<dl>\n<dt>Hotel Name</dt><dd>Qiqihaer Zhongtian Hotel</dd>\n<dt>City</dt><dd>Hulan Ergi</dd>\n<dt>Country</dt><dd>CN</dd>\n<dt>Max Temp</dt><dd>84.83 °F</dd>\n</dl>\n\n\n',
 '<dl>\n<dt>Hotel Name</dt><dd>Crowne Plaza Ordos</dd>\n<dt>City</dt><dd>Dongsheng</dd>\n<dt>Country</dt><dd>CN</dd>\n<dt>Max Temp</dt><dd>87.57 °F</dd>\n</dl>\n\n\n',
 '<dl>\n<dt>Hotel Name</dt><dd>Super Leisure Hotel</dd>\n<dt>City</dt><dd>Xining</dd>\n<dt>Country</dt><dd>CN</dd>\n<dt>Max Temp</dt><dd>78.8 °F</dd>\n</dl>\n\n\n']

In [11]:
# 11a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(40, 116), zoom_level=4)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))